#include <guile_thread.h>
#include <QDebug>

#include <libguile.h>
#include <editorController_guile.h>
#include <files.h>

// TODO make a real c-guile-registration system
static void* register_functions(void* data) {
  scm_c_define_gsubr("add-map!", 3, 0, 0, reinterpret_cast<scm_t_subr>(add_map));
  scm_c_define_gsubr("add-layer!", 1, 0, 0, reinterpret_cast<scm_t_subr>(add_layer));
  scm_c_define_gsubr("delete-root-index!", 2, 0, 0, reinterpret_cast<scm_t_subr>(delete_root_index));
  scm_c_define_gsubr("delete-layer!", 2, 0, 0, reinterpret_cast<scm_t_subr>(delete_layer));
  scm_c_define_gsubr("add-glsl-script!", 0, 0, 0, reinterpret_cast<scm_t_subr>(add_glsl_script));
  scm_c_define_gsubr("add-scheme-script!", 0, 0, 0, reinterpret_cast<scm_t_subr>(add_scheme_script));
  scm_c_define_gsubr("resize-current-map!", 4, 0, 0, reinterpret_cast<scm_t_subr>(resize_current_map));
  scm_c_define_gsubr("toggle-rendering!", 0, 0, 0, reinterpret_cast<scm_t_subr>(toggle_rendering));
  scm_c_define_gsubr("print-json!", 1, 0, 0, reinterpret_cast<scm_t_subr>(print_json));
  scm_c_define_gsubr("from-json!", 2, 0, 0, reinterpret_cast<scm_t_subr>(g_from_json));
  scm_c_define_gsubr("load-sprite!", 1, 0, 0, reinterpret_cast<scm_t_subr>(load_sprite));
  scm_c_define_gsubr("load-animation!", 3, 0, 0, reinterpret_cast<scm_t_subr>(load_animation));
  scm_c_define_gsubr("key-down?", 1, 0, 0, reinterpret_cast<scm_t_subr>(keyDown));
  scm_c_define_gsubr("get-mouse", 0, 0, 0, reinterpret_cast<scm_t_subr>(getMouse));
  
  return NULL;
}

Guile_Thread::Guile_Thread(int argc, char** argv): QThread(), argc(argc), argv(argv) {
}

void Guile_Thread::run() {
  scm_with_guile(&register_functions, NULL);
  scm_qt_key_pairs =
    {
      {scm_from_utf8_symbol("Key_Escape"), Qt::Key_Escape },
      {scm_from_utf8_symbol("Key_Tab"), Qt::Key_Tab },
      {scm_from_utf8_symbol("Key_Backtab"), Qt::Key_Backtab },
      {scm_from_utf8_symbol("Key_Backspace"), Qt::Key_Backspace },
      {scm_from_utf8_symbol("Key_Return"), Qt::Key_Return },
      {scm_from_utf8_symbol("Key_Enter"), Qt::Key_Enter },
      {scm_from_utf8_symbol("Key_Insert"), Qt::Key_Insert },
      {scm_from_utf8_symbol("Key_Delete"), Qt::Key_Delete },
      {scm_from_utf8_symbol("Key_Pause"), Qt::Key_Pause },
      {scm_from_utf8_symbol("Key_Print"), Qt::Key_Print },
      {scm_from_utf8_symbol("Key_SysReq"), Qt::Key_SysReq },
      {scm_from_utf8_symbol("Key_Clear"), Qt::Key_Clear },
      {scm_from_utf8_symbol("Key_Home"), Qt::Key_Home },
      {scm_from_utf8_symbol("Key_End"), Qt::Key_End },
      {scm_from_utf8_symbol("Key_Left"), Qt::Key_Left },
      {scm_from_utf8_symbol("Key_Up"), Qt::Key_Up },
      {scm_from_utf8_symbol("Key_Right"), Qt::Key_Right },
      {scm_from_utf8_symbol("Key_Down"), Qt::Key_Down },
      {scm_from_utf8_symbol("Key_PageUp"), Qt::Key_PageUp },
      {scm_from_utf8_symbol("Key_PageDown"), Qt::Key_PageDown },
      {scm_from_utf8_symbol("Key_Shift"), Qt::Key_Shift },
      {scm_from_utf8_symbol("Key_Control"), Qt::Key_Control },
      {scm_from_utf8_symbol("Key_Meta"), Qt::Key_Meta },
      {scm_from_utf8_symbol("Key_Alt"), Qt::Key_Alt },
      {scm_from_utf8_symbol("Key_CapsLock"), Qt::Key_CapsLock },
      {scm_from_utf8_symbol("Key_NumLock"), Qt::Key_NumLock },
      {scm_from_utf8_symbol("Key_ScrollLock"), Qt::Key_ScrollLock },
      {scm_from_utf8_symbol("Key_F1"), Qt::Key_F1 },
      {scm_from_utf8_symbol("Key_F2"), Qt::Key_F2 },
      {scm_from_utf8_symbol("Key_F3"), Qt::Key_F3 },
      {scm_from_utf8_symbol("Key_F4"), Qt::Key_F4 },
      {scm_from_utf8_symbol("Key_F5"), Qt::Key_F5 },
      {scm_from_utf8_symbol("Key_F6"), Qt::Key_F6 },
      {scm_from_utf8_symbol("Key_F7"), Qt::Key_F7 },
      {scm_from_utf8_symbol("Key_F8"), Qt::Key_F8 },
      {scm_from_utf8_symbol("Key_F9"), Qt::Key_F9 },
      {scm_from_utf8_symbol("Key_F10"), Qt::Key_F10 },
      {scm_from_utf8_symbol("Key_F11"), Qt::Key_F11 },
      {scm_from_utf8_symbol("Key_F12"), Qt::Key_F12 },
      {scm_from_utf8_symbol("Key_F13"), Qt::Key_F13 },
      {scm_from_utf8_symbol("Key_F14"), Qt::Key_F14 },
      {scm_from_utf8_symbol("Key_F15"), Qt::Key_F15 },
      {scm_from_utf8_symbol("Key_F16"), Qt::Key_F16 },
      {scm_from_utf8_symbol("Key_F17"), Qt::Key_F17 },
      {scm_from_utf8_symbol("Key_F18"), Qt::Key_F18 },
      {scm_from_utf8_symbol("Key_F19"), Qt::Key_F19 },
      {scm_from_utf8_symbol("Key_F20"), Qt::Key_F20 },
      {scm_from_utf8_symbol("Key_F21"), Qt::Key_F21 },
      {scm_from_utf8_symbol("Key_F22"), Qt::Key_F22 },
      {scm_from_utf8_symbol("Key_F23"), Qt::Key_F23 },
      {scm_from_utf8_symbol("Key_F24"), Qt::Key_F24 },
      {scm_from_utf8_symbol("Key_F25"), Qt::Key_F25 },
      {scm_from_utf8_symbol("Key_F26"), Qt::Key_F26 },
      {scm_from_utf8_symbol("Key_F27"), Qt::Key_F27 },
      {scm_from_utf8_symbol("Key_F28"), Qt::Key_F28 },
      {scm_from_utf8_symbol("Key_F29"), Qt::Key_F29 },
      {scm_from_utf8_symbol("Key_F30"), Qt::Key_F30 },
      {scm_from_utf8_symbol("Key_F31"), Qt::Key_F31 },
      {scm_from_utf8_symbol("Key_F32"), Qt::Key_F32 },
      {scm_from_utf8_symbol("Key_F33"), Qt::Key_F33 },
      {scm_from_utf8_symbol("Key_F34"), Qt::Key_F34 },
      {scm_from_utf8_symbol("Key_F35"), Qt::Key_F35 },
      {scm_from_utf8_symbol("Key_Super_L"), Qt::Key_Super_L },
      {scm_from_utf8_symbol("Key_Super_R"), Qt::Key_Super_R },
      {scm_from_utf8_symbol("Key_Menu"), Qt::Key_Menu },
      {scm_from_utf8_symbol("Key_Hyper_L"), Qt::Key_Hyper_L },
      {scm_from_utf8_symbol("Key_Hyper_R"), Qt::Key_Hyper_R },
      {scm_from_utf8_symbol("Key_Help"), Qt::Key_Help },
      {scm_from_utf8_symbol("Key_Direction_L"), Qt::Key_Direction_L },
      {scm_from_utf8_symbol("Key_Direction_R"), Qt::Key_Direction_R },
      {scm_from_utf8_symbol("Key_Space"), Qt::Key_Space },
      {scm_from_utf8_symbol("Key_Any"), Qt::Key_Any },
      {scm_from_utf8_symbol("Key_Exclam"), Qt::Key_Exclam },
      {scm_from_utf8_symbol("Key_QuoteDbl"), Qt::Key_QuoteDbl },
      {scm_from_utf8_symbol("Key_NumberSign"), Qt::Key_NumberSign },
      {scm_from_utf8_symbol("Key_Dollar"), Qt::Key_Dollar },
      {scm_from_utf8_symbol("Key_Percent"), Qt::Key_Percent },
      {scm_from_utf8_symbol("Key_Ampersand"), Qt::Key_Ampersand },
      {scm_from_utf8_symbol("Key_Apostrophe"), Qt::Key_Apostrophe },
      {scm_from_utf8_symbol("Key_ParenLeft"), Qt::Key_ParenLeft },
      {scm_from_utf8_symbol("Key_ParenRight"), Qt::Key_ParenRight },
      {scm_from_utf8_symbol("Key_Asterisk"), Qt::Key_Asterisk },
      {scm_from_utf8_symbol("Key_Plus"), Qt::Key_Plus },
      {scm_from_utf8_symbol("Key_Comma"), Qt::Key_Comma },
      {scm_from_utf8_symbol("Key_Minus"), Qt::Key_Minus },
      {scm_from_utf8_symbol("Key_Period"), Qt::Key_Period },
      {scm_from_utf8_symbol("Key_Slash"), Qt::Key_Slash },
      {scm_from_utf8_symbol("Key_0"), Qt::Key_0 },
      {scm_from_utf8_symbol("Key_1"), Qt::Key_1 },
      {scm_from_utf8_symbol("Key_2"), Qt::Key_2 },
      {scm_from_utf8_symbol("Key_3"), Qt::Key_3 },
      {scm_from_utf8_symbol("Key_4"), Qt::Key_4 },
      {scm_from_utf8_symbol("Key_5"), Qt::Key_5 },
      {scm_from_utf8_symbol("Key_6"), Qt::Key_6 },
      {scm_from_utf8_symbol("Key_7"), Qt::Key_7 },
      {scm_from_utf8_symbol("Key_8"), Qt::Key_8 },
      {scm_from_utf8_symbol("Key_9"), Qt::Key_9 },
      {scm_from_utf8_symbol("Key_Colon"), Qt::Key_Colon },
      {scm_from_utf8_symbol("Key_Semicolon"), Qt::Key_Semicolon },
      {scm_from_utf8_symbol("Key_Less"), Qt::Key_Less },
      {scm_from_utf8_symbol("Key_Equal"), Qt::Key_Equal },
      {scm_from_utf8_symbol("Key_Greater"), Qt::Key_Greater },
      {scm_from_utf8_symbol("Key_Question"), Qt::Key_Question },
      {scm_from_utf8_symbol("Key_At"), Qt::Key_At },
      {scm_from_utf8_symbol("Key_A"), Qt::Key_A },
      {scm_from_utf8_symbol("Key_B"), Qt::Key_B },
      {scm_from_utf8_symbol("Key_C"), Qt::Key_C },
      {scm_from_utf8_symbol("Key_D"), Qt::Key_D },
      {scm_from_utf8_symbol("Key_E"), Qt::Key_E },
      {scm_from_utf8_symbol("Key_F"), Qt::Key_F },
      {scm_from_utf8_symbol("Key_G"), Qt::Key_G },
      {scm_from_utf8_symbol("Key_H"), Qt::Key_H },
      {scm_from_utf8_symbol("Key_I"), Qt::Key_I },
      {scm_from_utf8_symbol("Key_J"), Qt::Key_J },
      {scm_from_utf8_symbol("Key_K"), Qt::Key_K },
      {scm_from_utf8_symbol("Key_L"), Qt::Key_L },
      {scm_from_utf8_symbol("Key_M"), Qt::Key_M },
      {scm_from_utf8_symbol("Key_N"), Qt::Key_N },
      {scm_from_utf8_symbol("Key_O"), Qt::Key_O },
      {scm_from_utf8_symbol("Key_P"), Qt::Key_P },
      {scm_from_utf8_symbol("Key_Q"), Qt::Key_Q },
      {scm_from_utf8_symbol("Key_R"), Qt::Key_R },
      {scm_from_utf8_symbol("Key_S"), Qt::Key_S },
      {scm_from_utf8_symbol("Key_T"), Qt::Key_T },
      {scm_from_utf8_symbol("Key_U"), Qt::Key_U },
      {scm_from_utf8_symbol("Key_V"), Qt::Key_V },
      {scm_from_utf8_symbol("Key_W"), Qt::Key_W },
      {scm_from_utf8_symbol("Key_X"), Qt::Key_X },
      {scm_from_utf8_symbol("Key_Y"), Qt::Key_Y },
      {scm_from_utf8_symbol("Key_Z"), Qt::Key_Z },
      {scm_from_utf8_symbol("Key_BracketLeft"), Qt::Key_BracketLeft },
      {scm_from_utf8_symbol("Key_Backslash"), Qt::Key_Backslash },
      {scm_from_utf8_symbol("Key_BracketRight"), Qt::Key_BracketRight },
      {scm_from_utf8_symbol("Key_AsciiCircum"), Qt::Key_AsciiCircum },
      {scm_from_utf8_symbol("Key_Underscore"), Qt::Key_Underscore },
      {scm_from_utf8_symbol("Key_QuoteLeft"), Qt::Key_QuoteLeft },
      {scm_from_utf8_symbol("Key_BraceLeft"), Qt::Key_BraceLeft },
      {scm_from_utf8_symbol("Key_Bar"), Qt::Key_Bar },
      {scm_from_utf8_symbol("Key_BraceRight"), Qt::Key_BraceRight },
      {scm_from_utf8_symbol("Key_AsciiTilde"), Qt::Key_AsciiTilde },
      {scm_from_utf8_symbol("Key_nobreakspace"), Qt::Key_nobreakspace },
      {scm_from_utf8_symbol("Key_exclamdown"), Qt::Key_exclamdown },
      {scm_from_utf8_symbol("Key_cent"), Qt::Key_cent },
      {scm_from_utf8_symbol("Key_sterling"), Qt::Key_sterling },
      {scm_from_utf8_symbol("Key_currency"), Qt::Key_currency },
      {scm_from_utf8_symbol("Key_yen"), Qt::Key_yen },
      {scm_from_utf8_symbol("Key_brokenbar"), Qt::Key_brokenbar },
      {scm_from_utf8_symbol("Key_section"), Qt::Key_section },
      {scm_from_utf8_symbol("Key_diaeresis"), Qt::Key_diaeresis },
      {scm_from_utf8_symbol("Key_copyright"), Qt::Key_copyright },
      {scm_from_utf8_symbol("Key_ordfeminine"), Qt::Key_ordfeminine },
      {scm_from_utf8_symbol("Key_guillemotleft"), Qt::Key_guillemotleft },
      {scm_from_utf8_symbol("Key_notsign"), Qt::Key_notsign },
      {scm_from_utf8_symbol("Key_hyphen"), Qt::Key_hyphen },
      {scm_from_utf8_symbol("Key_registered"), Qt::Key_registered },
      {scm_from_utf8_symbol("Key_macron"), Qt::Key_macron },
      {scm_from_utf8_symbol("Key_degree"), Qt::Key_degree },
      {scm_from_utf8_symbol("Key_plusminus"), Qt::Key_plusminus },
      {scm_from_utf8_symbol("Key_twosuperior"), Qt::Key_twosuperior },
      {scm_from_utf8_symbol("Key_threesuperior"), Qt::Key_threesuperior },
      {scm_from_utf8_symbol("Key_acute"), Qt::Key_acute },
      {scm_from_utf8_symbol("Key_mu"), Qt::Key_mu },
      {scm_from_utf8_symbol("Key_paragraph"), Qt::Key_paragraph },
      {scm_from_utf8_symbol("Key_periodcentered"), Qt::Key_periodcentered },
      {scm_from_utf8_symbol("Key_cedilla"), Qt::Key_cedilla },
      {scm_from_utf8_symbol("Key_onesuperior"), Qt::Key_onesuperior },
      {scm_from_utf8_symbol("Key_masculine"), Qt::Key_masculine },
      {scm_from_utf8_symbol("Key_guillemotright"), Qt::Key_guillemotright },
      {scm_from_utf8_symbol("Key_onequarter"), Qt::Key_onequarter },
      {scm_from_utf8_symbol("Key_onehalf"), Qt::Key_onehalf },
      {scm_from_utf8_symbol("Key_threequarters"), Qt::Key_threequarters },
      {scm_from_utf8_symbol("Key_questiondown"), Qt::Key_questiondown },
      {scm_from_utf8_symbol("Key_Agrave"), Qt::Key_Agrave },
      {scm_from_utf8_symbol("Key_Aacute"), Qt::Key_Aacute },
      {scm_from_utf8_symbol("Key_Acircumflex"), Qt::Key_Acircumflex },
      {scm_from_utf8_symbol("Key_Atilde"), Qt::Key_Atilde },
      {scm_from_utf8_symbol("Key_Adiaeresis"), Qt::Key_Adiaeresis },
      {scm_from_utf8_symbol("Key_Aring"), Qt::Key_Aring },
      {scm_from_utf8_symbol("Key_AE"), Qt::Key_AE },
      {scm_from_utf8_symbol("Key_Ccedilla"), Qt::Key_Ccedilla },
      {scm_from_utf8_symbol("Key_Egrave"), Qt::Key_Egrave },
      {scm_from_utf8_symbol("Key_Eacute"), Qt::Key_Eacute },
      {scm_from_utf8_symbol("Key_Ecircumflex"), Qt::Key_Ecircumflex },
      {scm_from_utf8_symbol("Key_Ediaeresis"), Qt::Key_Ediaeresis },
      {scm_from_utf8_symbol("Key_Igrave"), Qt::Key_Igrave },
      {scm_from_utf8_symbol("Key_Iacute"), Qt::Key_Iacute },
      {scm_from_utf8_symbol("Key_Icircumflex"), Qt::Key_Icircumflex },
      {scm_from_utf8_symbol("Key_Idiaeresis"), Qt::Key_Idiaeresis },
      {scm_from_utf8_symbol("Key_ETH"), Qt::Key_ETH },
      {scm_from_utf8_symbol("Key_Ntilde"), Qt::Key_Ntilde },
      {scm_from_utf8_symbol("Key_Ograve"), Qt::Key_Ograve },
{scm_from_utf8_symbol("Key_Oacute"), Qt::Key_Oacute },
    {scm_from_utf8_symbol("Key_Ocircumflex"), Qt::Key_Ocircumflex },
    {scm_from_utf8_symbol("Key_Otilde"), Qt::Key_Otilde },
    {scm_from_utf8_symbol("Key_Odiaeresis"), Qt::Key_Odiaeresis },
    {scm_from_utf8_symbol("Key_multiply"), Qt::Key_multiply },
    {scm_from_utf8_symbol("Key_Ooblique"), Qt::Key_Ooblique },
    {scm_from_utf8_symbol("Key_Ugrave"), Qt::Key_Ugrave },
    {scm_from_utf8_symbol("Key_Uacute"), Qt::Key_Uacute },
    {scm_from_utf8_symbol("Key_Ucircumflex"), Qt::Key_Ucircumflex },
    {scm_from_utf8_symbol("Key_Udiaeresis"), Qt::Key_Udiaeresis },
    {scm_from_utf8_symbol("Key_Yacute"), Qt::Key_Yacute },
    {scm_from_utf8_symbol("Key_THORN"), Qt::Key_THORN },
    {scm_from_utf8_symbol("Key_ssharp"), Qt::Key_ssharp },
    {scm_from_utf8_symbol("Key_division"), Qt::Key_division },
    {scm_from_utf8_symbol("Key_ydiaeresis"), Qt::Key_ydiaeresis },
    {scm_from_utf8_symbol("Key_AltGr              "), Qt::Key_AltGr               },
    {scm_from_utf8_symbol("Key_Multi_key          "), Qt::Key_Multi_key           },
    {scm_from_utf8_symbol("Key_Codeinput          "), Qt::Key_Codeinput           },
    {scm_from_utf8_symbol("Key_SingleCandidate    "), Qt::Key_SingleCandidate     },
    {scm_from_utf8_symbol("Key_MultipleCandidate  "), Qt::Key_MultipleCandidate   },
    {scm_from_utf8_symbol("Key_PreviousCandidate  "), Qt::Key_PreviousCandidate   },
    {scm_from_utf8_symbol("Key_Back "), Qt::Key_Back  },
    {scm_from_utf8_symbol("Key_Forward "), Qt::Key_Forward  },
    {scm_from_utf8_symbol("Key_Stop "), Qt::Key_Stop  },
    {scm_from_utf8_symbol("Key_Refresh "), Qt::Key_Refresh  },
    {scm_from_utf8_symbol("Key_VolumeDown"), Qt::Key_VolumeDown },
    {scm_from_utf8_symbol("Key_VolumeMute "), Qt::Key_VolumeMute  },
    {scm_from_utf8_symbol("Key_VolumeUp"), Qt::Key_VolumeUp },
    {scm_from_utf8_symbol("Key_BassBoost"), Qt::Key_BassBoost },
    {scm_from_utf8_symbol("Key_BassUp"), Qt::Key_BassUp },
    {scm_from_utf8_symbol("Key_BassDown"), Qt::Key_BassDown },
    {scm_from_utf8_symbol("Key_TrebleUp"), Qt::Key_TrebleUp },
    {scm_from_utf8_symbol("Key_TrebleDown"), Qt::Key_TrebleDown },
    {scm_from_utf8_symbol("Key_MediaPlay "), Qt::Key_MediaPlay  },
    {scm_from_utf8_symbol("Key_MediaStop "), Qt::Key_MediaStop  },
    {scm_from_utf8_symbol("Key_MediaPrevious "), Qt::Key_MediaPrevious  },
    {scm_from_utf8_symbol("Key_MediaNext "), Qt::Key_MediaNext  },
    {scm_from_utf8_symbol("Key_MediaRecord"), Qt::Key_MediaRecord },
    {scm_from_utf8_symbol("Key_MediaPause"), Qt::Key_MediaPause },
    {scm_from_utf8_symbol("Key_MediaTogglePlayPause"), Qt::Key_MediaTogglePlayPause },
    {scm_from_utf8_symbol("Key_HomePage "), Qt::Key_HomePage  },
    {scm_from_utf8_symbol("Key_Favorites "), Qt::Key_Favorites  },
    {scm_from_utf8_symbol("Key_Search "), Qt::Key_Search  },
    {scm_from_utf8_symbol("Key_Standby"), Qt::Key_Standby },
    {scm_from_utf8_symbol("Key_OpenUrl"), Qt::Key_OpenUrl },
    {scm_from_utf8_symbol("Key_LaunchMail "), Qt::Key_LaunchMail  },
    {scm_from_utf8_symbol("Key_LaunchMedia"), Qt::Key_LaunchMedia },
    {scm_from_utf8_symbol("Key_Launch0 "), Qt::Key_Launch0  },
    {scm_from_utf8_symbol("Key_Launch1 "), Qt::Key_Launch1  },
    {scm_from_utf8_symbol("Key_Launch2 "), Qt::Key_Launch2  },
    {scm_from_utf8_symbol("Key_Launch3 "), Qt::Key_Launch3  },
    {scm_from_utf8_symbol("Key_Launch4 "), Qt::Key_Launch4  },
    {scm_from_utf8_symbol("Key_Launch5 "), Qt::Key_Launch5  },
    {scm_from_utf8_symbol("Key_Launch6 "), Qt::Key_Launch6  },
    {scm_from_utf8_symbol("Key_Launch7 "), Qt::Key_Launch7  },
    {scm_from_utf8_symbol("Key_Launch8 "), Qt::Key_Launch8  },
    {scm_from_utf8_symbol("Key_Launch9 "), Qt::Key_Launch9  },
    {scm_from_utf8_symbol("Key_LaunchA "), Qt::Key_LaunchA  },
    {scm_from_utf8_symbol("Key_LaunchB "), Qt::Key_LaunchB  },
    {scm_from_utf8_symbol("Key_LaunchC "), Qt::Key_LaunchC  },
    {scm_from_utf8_symbol("Key_LaunchD "), Qt::Key_LaunchD  },
    {scm_from_utf8_symbol("Key_LaunchE "), Qt::Key_LaunchE  },
    {scm_from_utf8_symbol("Key_LaunchF "), Qt::Key_LaunchF  },
    {scm_from_utf8_symbol("Key_MonBrightnessUp"), Qt::Key_MonBrightnessUp },
    {scm_from_utf8_symbol("Key_MonBrightnessDown"), Qt::Key_MonBrightnessDown },
    {scm_from_utf8_symbol("Key_PowerOff"), Qt::Key_PowerOff },
    {scm_from_utf8_symbol("Key_WakeUp"), Qt::Key_WakeUp },
    {scm_from_utf8_symbol("Key_Eject"), Qt::Key_Eject },
    {scm_from_utf8_symbol("Key_ScreenSaver"), Qt::Key_ScreenSaver },
    {scm_from_utf8_symbol("Key_WWW"), Qt::Key_WWW },
    {scm_from_utf8_symbol("Key_Memo"), Qt::Key_Memo },
    {scm_from_utf8_symbol("Key_LightBulb"), Qt::Key_LightBulb },
    {scm_from_utf8_symbol("Key_Shop"), Qt::Key_Shop },
    {scm_from_utf8_symbol("Key_History"), Qt::Key_History },
    {scm_from_utf8_symbol("Key_AddFavorite"), Qt::Key_AddFavorite },
    {scm_from_utf8_symbol("Key_HotLinks"), Qt::Key_HotLinks },
    {scm_from_utf8_symbol("Key_BrightnessAdjust"), Qt::Key_BrightnessAdjust },
    {scm_from_utf8_symbol("Key_Finance"), Qt::Key_Finance },
    {scm_from_utf8_symbol("Key_Community"), Qt::Key_Community },
    {scm_from_utf8_symbol("Key_AudioRewind"), Qt::Key_AudioRewind },
    {scm_from_utf8_symbol("Key_BackForward"), Qt::Key_BackForward },
    {scm_from_utf8_symbol("Key_ApplicationLeft"), Qt::Key_ApplicationLeft },
    {scm_from_utf8_symbol("Key_ApplicationRight"), Qt::Key_ApplicationRight },
    {scm_from_utf8_symbol("Key_Book"), Qt::Key_Book },
    {scm_from_utf8_symbol("Key_CD"), Qt::Key_CD },
    {scm_from_utf8_symbol("Key_Calculator"), Qt::Key_Calculator },
    {scm_from_utf8_symbol("Key_ToDoList"), Qt::Key_ToDoList },
    {scm_from_utf8_symbol("Key_ClearGrab"), Qt::Key_ClearGrab },
    {scm_from_utf8_symbol("Key_Close"), Qt::Key_Close },
    {scm_from_utf8_symbol("Key_Copy"), Qt::Key_Copy },
    {scm_from_utf8_symbol("Key_Cut"), Qt::Key_Cut },
    {scm_from_utf8_symbol("Key_Display"), Qt::Key_Display },
    {scm_from_utf8_symbol("Key_DOS"), Qt::Key_DOS },
    {scm_from_utf8_symbol("Key_Documents"), Qt::Key_Documents },
    {scm_from_utf8_symbol("Key_Excel"), Qt::Key_Excel },
    {scm_from_utf8_symbol("Key_Explorer"), Qt::Key_Explorer },
    {scm_from_utf8_symbol("Key_Game"), Qt::Key_Game },
    {scm_from_utf8_symbol("Key_Go"), Qt::Key_Go },
    {scm_from_utf8_symbol("Key_iTouch"), Qt::Key_iTouch },
    {scm_from_utf8_symbol("Key_LogOff"), Qt::Key_LogOff },
    {scm_from_utf8_symbol("Key_Market"), Qt::Key_Market },
    {scm_from_utf8_symbol("Key_Meeting"), Qt::Key_Meeting },
    {scm_from_utf8_symbol("Key_MenuKB"), Qt::Key_MenuKB },
    {scm_from_utf8_symbol("Key_MenuPB"), Qt::Key_MenuPB },
    {scm_from_utf8_symbol("Key_MySites"), Qt::Key_MySites },
    {scm_from_utf8_symbol("Key_News"), Qt::Key_News },
    {scm_from_utf8_symbol("Key_OfficeHome"), Qt::Key_OfficeHome },
    {scm_from_utf8_symbol("Key_Option"), Qt::Key_Option },
    {scm_from_utf8_symbol("Key_Paste"), Qt::Key_Paste },
    {scm_from_utf8_symbol("Key_Phone"), Qt::Key_Phone },
    {scm_from_utf8_symbol("Key_Calendar"), Qt::Key_Calendar },
    {scm_from_utf8_symbol("Key_Reply"), Qt::Key_Reply },
    {scm_from_utf8_symbol("Key_Reload"), Qt::Key_Reload },
    {scm_from_utf8_symbol("Key_RotateWindows"), Qt::Key_RotateWindows },
    {scm_from_utf8_symbol("Key_RotationPB"), Qt::Key_RotationPB },
    {scm_from_utf8_symbol("Key_RotationKB"), Qt::Key_RotationKB },
    {scm_from_utf8_symbol("Key_Save"), Qt::Key_Save },
    {scm_from_utf8_symbol("Key_Send"), Qt::Key_Send },
    {scm_from_utf8_symbol("Key_Spell"), Qt::Key_Spell },
    {scm_from_utf8_symbol("Key_SplitScreen"), Qt::Key_SplitScreen },
    {scm_from_utf8_symbol("Key_Support"), Qt::Key_Support },
    {scm_from_utf8_symbol("Key_TaskPane"), Qt::Key_TaskPane },
    {scm_from_utf8_symbol("Key_Terminal"), Qt::Key_Terminal },
    {scm_from_utf8_symbol("Key_Tools"), Qt::Key_Tools },
    {scm_from_utf8_symbol("Key_Travel"), Qt::Key_Travel },
    {scm_from_utf8_symbol("Key_Video"), Qt::Key_Video },
    {scm_from_utf8_symbol("Key_Word"), Qt::Key_Word },
    {scm_from_utf8_symbol("Key_Xfer"), Qt::Key_Xfer },
    {scm_from_utf8_symbol("Key_ZoomIn"), Qt::Key_ZoomIn },
    {scm_from_utf8_symbol("Key_ZoomOut"), Qt::Key_ZoomOut },
    {scm_from_utf8_symbol("Key_Away"), Qt::Key_Away },
    {scm_from_utf8_symbol("Key_Messenger"), Qt::Key_Messenger },
    {scm_from_utf8_symbol("Key_WebCam"), Qt::Key_WebCam },
    {scm_from_utf8_symbol("Key_MailForward"), Qt::Key_MailForward },
    {scm_from_utf8_symbol("Key_Pictures"), Qt::Key_Pictures },
    {scm_from_utf8_symbol("Key_Music"), Qt::Key_Music },
    {scm_from_utf8_symbol("Key_Battery"), Qt::Key_Battery },
    {scm_from_utf8_symbol("Key_Bluetooth"), Qt::Key_Bluetooth },
    {scm_from_utf8_symbol("Key_WLAN"), Qt::Key_WLAN },
    {scm_from_utf8_symbol("Key_UWB"), Qt::Key_UWB },
    {scm_from_utf8_symbol("Key_AudioForward"), Qt::Key_AudioForward },
    {scm_from_utf8_symbol("Key_AudioRepeat"), Qt::Key_AudioRepeat },
    {scm_from_utf8_symbol("Key_AudioRandomPlay"), Qt::Key_AudioRandomPlay },
    {scm_from_utf8_symbol("Key_Subtitle"), Qt::Key_Subtitle },
    {scm_from_utf8_symbol("Key_AudioCycleTrack"), Qt::Key_AudioCycleTrack },
    {scm_from_utf8_symbol("Key_Time"), Qt::Key_Time },
    {scm_from_utf8_symbol("Key_Hibernate"), Qt::Key_Hibernate },
    {scm_from_utf8_symbol("Key_View"), Qt::Key_View },
    {scm_from_utf8_symbol("Key_TopMenu"), Qt::Key_TopMenu },
    {scm_from_utf8_symbol("Key_PowerDown"), Qt::Key_PowerDown },
    {scm_from_utf8_symbol("Key_Suspend"), Qt::Key_Suspend },
    {scm_from_utf8_symbol("Key_ContrastAdjust"), Qt::Key_ContrastAdjust },

    {scm_from_utf8_symbol("Key_LaunchG "), Qt::Key_LaunchG  },
    {scm_from_utf8_symbol("Key_LaunchH "), Qt::Key_LaunchH  },

    {scm_from_utf8_symbol("Key_TouchpadToggle"), Qt::Key_TouchpadToggle },
    {scm_from_utf8_symbol("Key_TouchpadOn"), Qt::Key_TouchpadOn },
    {scm_from_utf8_symbol("Key_TouchpadOff"), Qt::Key_TouchpadOff },

    {scm_from_utf8_symbol("Key_MicMute"), Qt::Key_MicMute },

    {scm_from_utf8_symbol("Key_Red"), Qt::Key_Red },
    {scm_from_utf8_symbol("Key_Green"), Qt::Key_Green },
    {scm_from_utf8_symbol("Key_Yellow"), Qt::Key_Yellow },
    {scm_from_utf8_symbol("Key_Blue"), Qt::Key_Blue },

    {scm_from_utf8_symbol("Key_ChannelUp"), Qt::Key_ChannelUp },
    {scm_from_utf8_symbol("Key_ChannelDown"), Qt::Key_ChannelDown },

    {scm_from_utf8_symbol("Key_Guide   "), Qt::Key_Guide    },
    {scm_from_utf8_symbol("Key_Info    "), Qt::Key_Info     },
    {scm_from_utf8_symbol("Key_Settings"), Qt::Key_Settings },

    {scm_from_utf8_symbol("Key_MicVolumeUp  "), Qt::Key_MicVolumeUp   },
    {scm_from_utf8_symbol("Key_MicVolumeDown"), Qt::Key_MicVolumeDown },

    {scm_from_utf8_symbol("Key_New     "), Qt::Key_New      },
    {scm_from_utf8_symbol("Key_Open    "), Qt::Key_Open     },
    {scm_from_utf8_symbol("Key_Find    "), Qt::Key_Find     },
    {scm_from_utf8_symbol("Key_Undo    "), Qt::Key_Undo     },
    {scm_from_utf8_symbol("Key_Redo    "), Qt::Key_Redo     },

    {scm_from_utf8_symbol("Key_MediaLast"), Qt::Key_MediaLast },

    {scm_from_utf8_symbol("Key_Select"), Qt::Key_Select },
    {scm_from_utf8_symbol("Key_Yes"), Qt::Key_Yes },
    {scm_from_utf8_symbol("Key_No"), Qt::Key_No },

    // Newer misc keys
    {scm_from_utf8_symbol("Key_Cancel "), Qt::Key_Cancel  },
    {scm_from_utf8_symbol("Key_Printer"), Qt::Key_Printer },
    {scm_from_utf8_symbol("Key_Execute"), Qt::Key_Execute },
    {scm_from_utf8_symbol("Key_Sleep  "), Qt::Key_Sleep   },
    {scm_from_utf8_symbol("Key_Play   "), Qt::Key_Play    },
    {scm_from_utf8_symbol("Key_Zoom   "), Qt::Key_Zoom    },
    {scm_from_utf8_symbol("Key_Exit   "), Qt::Key_Exit    },

    // Device keys
    {scm_from_utf8_symbol("Key_Context1"), Qt::Key_Context1 },
    {scm_from_utf8_symbol("Key_Context2"), Qt::Key_Context2 },
    {scm_from_utf8_symbol("Key_Context3"), Qt::Key_Context3 },
    {scm_from_utf8_symbol("Key_Context4"), Qt::Key_Context4 },
    {scm_from_utf8_symbol("Key_Call"), Qt::Key_Call },
    {scm_from_utf8_symbol("Key_Hangup"), Qt::Key_Hangup },
    {scm_from_utf8_symbol("Key_Flip"), Qt::Key_Flip },
    {scm_from_utf8_symbol("Key_ToggleCallHangup"), Qt::Key_ToggleCallHangup },
    {scm_from_utf8_symbol("Key_VoiceDial"), Qt::Key_VoiceDial },
    {scm_from_utf8_symbol("Key_LastNumberRedial"), Qt::Key_LastNumberRedial },
    {scm_from_utf8_symbol("Key_Camera"), Qt::Key_Camera },
    {scm_from_utf8_symbol("Key_CameraFocus"), Qt::Key_CameraFocus },
    {scm_from_utf8_symbol("Key_unknown"), Qt::Key_unknown },
  };


  scm_c_primitive_load((QCoreApplication::applicationDirPath() +"/"+"./qmapper_std.scm").toStdString().c_str());
  
  scm_shell(argc, argv);
}
